default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: king_dev

test:
  <<: *default
  database: king_test


production:
  <<: *default
  database: king_production
  username: genesis_hr_portal
  password: <%= ENV['GENESIS_HR_PORTAL_DATABASE_PASSWORD'] %>
